[[classOrder]]
classes = ["Axis"]

[[classOrder]]
section = "Configs"
classes = [
    "PlayerConfig",
]

[[classOrder]]
section = "Core"
classes = [
    "ServerBootstrap",
    "ClientBootstrap",
    "ModuleSystem",
    "ControllerSystem",
]

[[classOrder]]
section = "Controllers"
classes = [
    "PlayerController",
    "CameraController",
]

gitSourceBranch = "Main"

[footer]
style = "dark"
copyright = "Copyright © 2024 Sebastian2852. Built with Moonwave and Docusaurus"