[package]
name = "sebastian2852/axis"
description = "Framework inspired by Knit"
version = "0.0.10"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

license = "Apache"
authors = ["sebastian2852"]

[dependencies]
Promise = "evaera/promise@4.0.0"
Comm = "sleitnick/comm@1.0.1"